.TH "eiskaltdcpp-daemon" 1 "16 Oct 2011"
.SH "NAME"
eiskaltdcpp-daemon \- simple daemon controllable via XML-RPC
.SH "SYNOPSIS"
.PP
.B eiskaltdcpp-daemon
\-d
.br
.B eiskaltdcpp-daemon
<Key>
.SH "DESCRIPTION"
.PP
\fBEiskaltDC++\fP is a cross-platform program that uses the Direct Connect and ADC protocol. It is compatible with other DC clients, such as the original DC from Neomodus, DC++ and derivatives. EiskaltDC++ also interoperates with all common DC hub software.
.SH "COMMAND LINE OPTIONS"
.RB "A summary of options is included below."
.TP
.BR "\-d",  \-\-daemon"
Run program as daemon
.TP
.BR "\-V",  \-\-verbose"
Verbose mode
.TP
.BR "\-P <port>",  \-\-port=<port>"
Set port for XMLRPC (default: 3121)
.TP
.BR "\-p file",  \-\-pidfile=<file>"
Write daemon process ID to <file>
.TP
.BR "\-c dir",  \-\-confdir=<dir>"
Store config in <dir>
.TP
.BR "\-l <dir>",  \-\-localdir=<dir>"
Store local data (cache, temp files) in <dir> (defaults is equal confdir)
.TP
.BR "\-h,  \-\-help"
Display help and exit
.TP
.BR "\-v,  \-\-version"
Show version information and exit
.SH "FILES"
.TP
.B "~/.config/eiskaltdc++/" or "$XDG_CONFIG_HOME/eiskaltdc++/"
Directory with user configuration files
.SH "DOCUMENTATION"
.TP
Detail documentation about available XML-RPC methods can be found in our wiki: \fBhttp://code.google.com/p/eiskaltdc/wiki/XMLRPC\fR
.SH AUTHOR
This program was written by EiskaltDC++ developers team (see file AUTHORS).
.br
EiskaltDC++ homepage: \fBhttp://code.google.com/p/eiskaltdc/\fR
.SH "BUG REPORTS"
If you find a bug in EiskaltDC++ please report it here:
.B http://code.google.com/p/eiskaltdc/issues/list
.PP
This manual page was written by Boris Pek <tehnick-8@mail.ru> for the Debian project (and may be used by others).
