.TH "eiskaltdcpp-wt" 1 "23 Jul 2010"
.SH "NAME"
"EiskaltDC++ Wt" \- GUI based on Wt (Web Toolkit)
.SH "SYNOPSIS"
.PP
.B eiskaltdcpp-wt
--http-port=<port> --http-address=<address> --docroot <path>
.br
.B eiskaltdcpp-wt
<Key>
.SH "DESCRIPTION"
.PP
\fBEiskaltDC++\fP is a program for UNIX-like systems that uses the Direct Connect and ADC protocol. It is compatible with other DC clients, such as the original DC from Neomodus, DC++ and derivatives. EiskaltDC++ also interoperates with all common DC hub software.
.SH "COMMAND LINE OPTIONS"
.RB "A summary of options is included below."
.TP
.BR "\-h,  \-\-help"
display help and exit
.TP
.BR "\-v,  \-\-version"
output version information and exit
.SH "EXAMPLES"
.TP
.B "eiskaltdcpp-wt --http-port=8080 --http-address=0.0.0.0 --docroot /usr/share/eiskaltdcpp/wt/"
.SH "FILES"
.TP
.B "/usr/share/eiskaltdcpp/wt"
Directory with resource files
.SH AUTHOR
This program was written by Andrey Karlov <dein.negativ@gmail.com> and others (see file AUTHORS).
.br
EiskaltDC++ homepage: \fBhttp://code.google.com/p/eiskaltdc/\fR
.SH "BUG REPORTS"
If you find a bug in EiskaltDC++ please report it here:
.B http://code.google.com/p/eiskaltdc/issues/list
.PP
This manual page was written by Boris Pek <tehnick-8@mail.ru> for the Debian project (and may be used by others).
