.TH "eiskaltdcpp-qt" 1 "16 Oct 2011"
.SH "NAME"
EiskaltDC++_Qt \- GUI based on Qt
.SH "SYNOPSIS"
.PP
.B eiskaltdcpp-qt
<magnet link> <dchub://link> <adc(s)://link>
.br
.B eiskaltdcpp-qt
<Key>
.SH "DESCRIPTION"
.PP
\fBEiskaltDC++\fP is a cross-platform program that uses the Direct Connect and ADC protocol. It is compatible with other DC clients, such as the original DC from Neomodus, DC++ and derivatives. EiskaltDC++ also interoperates with all common DC hub software.
.SH "COMMAND LINE OPTIONS"
.RB "A summary of options is included below."
.TP
.BR "\-h,  \-\-help"
display help and exit
.TP
.BR "\-v,  \-\-version"
output version information and exit
.SH "KEYBOARD SHORTCUTS"
.RB "These are default keyboard shortcuts. You can change them in Preferences dialog (Shorcuts tab)."
.TP
.B "Ctrl+O"
Open options window
.TP
.B "Ctrl+L"
Open own filelist
.TP
.B "Ctrl+E"
Refresh share
.TP
.B "Ctrl+R"
Reconnect to hub
.TP
.B "Ctrl+N"
Quick connect
.TP
.B "Ctrl+H"
Favourite hubs
.TP
.B "Ctrl+P"
Public hubs
.TP
.B "Ctrl+U"
Favourite users
.TP
.B "Ctrl+T"
Show/hide transfers widget
.TP
.B "Ctrl+D"
Show/hide downloads queue widget
.TP
.B "Ctrl+S"
Open search widget
.TP
.B "Ctrl+F"
Show/hide find or filter frame
.TP
.B "Ctrl+A"
Select all
.TP
.B "Ctrl+W"
Close current widget
.TP
.B "Ctrl+M"
Show/hide main menu
.TP
.B "Ctrl+PageUp"
Switch to the previous widget. Available only if widget panel is used, not working in mode of sidebar.
.TP
.B "Ctrl+PageDown"
Switch to the next widget. Available only if widget panel is used, not working in mode of sidebar.
.TP
.B "Ctrl+Up"
Switch to the previous string from history of sent messages in chat for current session. Available only when input frame is focused on.
.TP
.B "Ctrl+Down"
Switch to the next string from history of sent messages in chat for current session. Available only when input frame is focused on.
.TP
.B "Ctrl++"
Zoom in text in the chat
.TP
.B "Ctrl+-"
Zoom out text in the chat
.TP
.B "Ctrl+Mousewheel"
Change font size in the chat
.TP
.B "Alt+<0-9>"
Go to one of the first ten widgets. Available only if widget panel is used, not working in mode of sidebar.
.TP
.B "Esc"
Hide find or filter frame. Also it close dialog window. Otherwise hide main window in tray (if tray icon is enabled)
.TP
.B "Del"
Delete selected items. Now available in Download Queue widget.
.SH "CHAT COMMANDS"
/aspell on/off \- enable/disable spell checking (only if program was build with aspell support)
.br
/alias <ALIAS_NAME>::<COMMAND> \- make alias /ALIAS_NAME to /COMMAND
    For example, command
    /alias amarok::/sh /usr/share/eiskaltdcpp/examples/amr.en_US.sh
    will create alias /amarok
.br
/alias purge <ALIAS_NAME> \- remove alias
.br
/alias list \- list all aliases
.br
/away <message> \- set away-mode on/off
.br
/back \- set away-mode off
.br
/browse <nick> \- browse user files
.br
/clear \- clear chat window
.br
/kword add <keyword> \- add user-defined keyword
.br
/kword purge <keyword> \- remove user-defined keyword
.br
/kword list \- list all keywords
.br
/magnet \- default action with magnet (0-ask, 1-search, 2-download)
.br
/close \- close this hub
.br
/fav \- add this hub to favorites
.br
/grant <nick> \- grant extra slot to user
.br
/help, /?, /h \- show help
.br
/info <nick> \- show info about user
.br
/ratio [show] \- show ratio [send in chat]
.br
/me \- say a third person
.br
/pm <nick> \- begin private chat with user
.br
/sh <command> \- start command and redirect output to the chat
.br
/luafile <file> \- load Lua file
.br
/lua <chunk> \- execute Lua Chunk
.br
/ws <option> [value] \- edit config (~/.config/eiskaltdc++/EiskaltDC++_Qt.conf), also you can edit it manually
    For example:
    /ws chat-dbl-click-action <0-2> (double click)
    /ws chat-mdl-click-action <0-2> (middle click)
    (0 \- insert nick into input widget, 1 \- get file list, 2 \- private message)
    /ws app-unit-base <1024 or 1000> (show kibibyte (KiB) or kilobyte (KB), etc.)
    /ws chat-timestamp <hh:mm:ss, hh:mm, hh and etc.> (set chat timestamp)
    /ws hubframe/chat-background-color <color> (set background color in the chat, where <color> is in HTML format)
    /ws hubframe/unreaden-draw-line <0-1> (0 \- switch off, 1 \- switch on)
    /ws hubframe/redirect-pm-to-main-chat <0-1> (see above)
.SH "FILES"
.TP
.B "/usr/share/eiskaltdcpp/qt"
Directory with some resource files
.TP
.B "~/.config/eiskaltdc++/" or "$XDG_CONFIG_HOME/eiskaltdc++/"
Directory with configuration files
.TP
.B "/usr/share/eiskaltdcpp/examples"
Directory with examples of custom scripts (see /sh chat command)
.SH AUTHOR
This program was written by Andrey Karlov <dein.negativ@gmail.com> and others (see file AUTHORS).
.br
EiskaltDC++ homepage: \fBhttp://code.google.com/p/eiskaltdc/\fR
.SH "BUG REPORTS"
If you find a bug in EiskaltDC++ please report it here:
.B http://code.google.com/p/eiskaltdc/issues/list
.PP
This manual page was written by Boris Pek <tehnick-8@mail.ru> for the Debian project (and may be used by others).
