if(CANBERRA_INCLUDE_DIR AND CANBERRA_LIBRARY)
  set(CANBERRA_FIND_QUIETLY TRUE)
endif(CANBERRA_INCLUDE_DIR AND CANBERRA_LIBRARY)

find_path(CANBERRA_INCLUDE_DIR canberra.h)
find_library(CANBERRA_LIBRARY canberra)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CANBERRA DEFAULT_MSG CANBERRA_LIBRARY CANBERRA_INCLUDE_DIR)

MARK_AS_ADVANCED(
  CANBERRA_INCLUDE_DIR
  CANBERRA_LIBRARY
)
