find_path(MINIUPNP_INCLUDE_DIR miniupnpc/miniupnpc.h
   PATH_SUFFIXES miniupnpc)
find_library(MINIUPNP_LIBRARY miniupnpc)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Miniupnpc DEFAULT_MSG MINIUPNP_LIBRARY MINIUPNP_INCLUDE_DIR)

MARK_AS_ADVANCED(
  MINIUPNP_INCLUDE_DIR
  MINIUPNP_LIBRARY
)
